#!/usr/bin/env bash
# Generate self-signed CA + client cert/key for ESP32 mTLS
# Outputs PEM files AND C header files for direct embedding.
#
# Usage:
#   cd hardware/esp32
#   bash scripts/gen_esp32_certs.sh S-ESP32-001
#
# Outputs (in hardware/esp32/):
#   certs/ca.crt      certs/client.crt      certs/client.key
#   certs/ca_cert.h   certs/client_cert.h   certs/client_key.h

set -euo pipefail

SENSOR_ID="${1:-S-ESP32-001}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="$(dirname "$SCRIPT_DIR")/certs"

mkdir -p "$OUT_DIR"

echo "[gen] Generating CA + client certificates for ${SENSOR_ID} ..."

# ─── CA ───────────────────────────────────────────────────────────────────────
openssl genrsa -out "$OUT_DIR/ca.key" 2048 2>/dev/null
openssl req -x509 -new -nodes -key "$OUT_DIR/ca.key" -sha256 -days 1825 \
  -subj "/C=LB/O=Omni-Sense/CN=Omni-Sense CA" \
  -out "$OUT_DIR/ca.crt"

# ─── Client key + CSR ─────────────────────────────────────────────────────────
openssl genrsa -out "$OUT_DIR/client.key" 2048 2>/dev/null
openssl req -new -key "$OUT_DIR/client.key" \
  -subj "/C=LB/O=Omni-Sense/CN=${SENSOR_ID}" \
  -out "$OUT_DIR/client.csr"

# ─── Sign client cert ─────────────────────────────────────────────────────────
openssl x509 -req -in "$OUT_DIR/client.csr" -CA "$OUT_DIR/ca.crt" \
  -CAkey "$OUT_DIR/ca.key" -CAcreateserial \
  -out "$OUT_DIR/client.crt" -days 365 -sha256

rm -f "$OUT_DIR/client.csr" "$OUT_DIR/ca.srl"

# ─── Helper: PEM → C string header ────────────────────────────────────────────
pem_to_header() {
  local pem_file="$1"
  local var_name="$2"
  local header_file="$3"
  local guard="$(basename "$header_file" | tr '[:lower:].' '[:upper:]_')"

  {
    echo "#ifndef ${guard}"
    echo "#define ${guard}"
    echo ""
    echo "// Auto-generated by gen_esp32_certs.sh — DO NOT EDIT"
    echo "// Source: $(basename "$pem_file")"
    echo ""
    echo "static const char ${var_name}[] PROGMEM = R\"EOF("
    cat "$pem_file"
    echo ")EOF\";"
    echo ""
    echo "#endif // ${guard}"
  } > "$header_file"
}

pem_to_header "$OUT_DIR/ca.crt"     "CA_CERT"     "$OUT_DIR/ca_cert.h"
pem_to_header "$OUT_DIR/client.crt" "CLIENT_CERT" "$OUT_DIR/client_cert.h"
pem_to_header "$OUT_DIR/client.key" "CLIENT_KEY"  "$OUT_DIR/client_key.h"

echo "[gen] Done."
echo "      PEM:  ${OUT_DIR}/{ca,client}.{crt,key}"
echo "      Headers: ${OUT_DIR}/{ca_cert,client_cert,client_key}.h"
echo ""
echo "[gen] Next steps:"
echo "      1. Copy certs/ca.crt to your Mosquitto broker's ca.crt"
echo "      2. Add the client cert/key to mosquitto/config/acl or pwfile"
echo "      3. Include the generated .h files in omni_sensor.ino"
