apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.eep.name }}
  namespace: {{ include "omni-sense.namespace" . }}
  labels:
    {{- include "omni-sense.componentLabels" (dict "component" .Values.eep.name "context" .) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "omni-sense.selectorLabels" (dict "component" .Values.eep.name "context" .) | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.eep.port }}
      targetPort: http
      protocol: TCP
