/**
 * edge_model_data.h — auto-generated by scripts/tflite_to_c_array.py
 * DO NOT EDIT BY HAND. Regenerate by training the autoencoder and
 * running the conversion script (see scripts/train_edge_autoencoder.py).
 */
#pragma once
#include <stdint.h>

// Placeholder — TensorFlow was not available at generation time.
// The firmware checks edge_model_is_valid() at boot and falls back
// to the raw-PCM publish path automatically.
#define OMNI_EDGE_MODEL_PLACEHOLDER 1

#ifdef __cplusplus
extern "C" {
#endif

// 16 bytes of int8-quantised TFLite-Micro model.
alignas(16) const unsigned char omni_edge_model_data[] = {
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
};
const unsigned int omni_edge_model_data_len = 16;

// Reconstruction-MSE threshold above which the device flags OOD.
const float omni_edge_threshold = 0.500000f;

#ifdef __cplusplus
}  // extern "C"
#endif
