"""
Convert a .tflite model into a C header file suitable for TFLite-Micro.

Output header
-------------
    extern const unsigned char model_data[];
    extern const unsigned int  model_data_len;

The array is 16-byte-aligned via __attribute__((aligned(16))) so the
TFLite-Micro interpreter can mmap it directly without a copy.

Usage
-----
    py -3.12 scripts/tflite_to_c_array.py \\
        --input  iep2/models/edge_autoencoder.tflite \\
        --output hardware/esp32/omni_sensor/edge_model_data.h \\
        --threshold-json iep2/models/edge_threshold.json

The threshold JSON (if given) is also baked in as a const float in the
header — saves the firmware one filesystem read at boot.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from textwrap import wrap

PROJ = Path(__file__).parent.parent


def emit_header(
    tflite_bytes: bytes,
    threshold:    float | None,
    feat_mean:    list[float] | None,
    feat_std:     list[float] | None,
    out_path:     Path,
    is_placeholder: bool,
) -> None:
    n = len(tflite_bytes)
    rows = []
    for i in range(0, n, 12):
        chunk = tflite_bytes[i:i + 12]
        rows.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")

    lines = [
        "/**",
        " * edge_model_data.h — auto-generated by scripts/tflite_to_c_array.py",
        " * DO NOT EDIT BY HAND. Regenerate by training the autoencoder and",
        " * running the conversion script (see scripts/train_edge_autoencoder.py).",
        " */",
        "#pragma once",
        "#include <stdint.h>",
        "",
    ]
    if is_placeholder:
        lines += [
            "// Placeholder — TensorFlow was not available at generation time.",
            "// The firmware checks edge_model_is_valid() at boot and falls back",
            "// to the raw-PCM publish path automatically.",
            "#define OMNI_EDGE_MODEL_PLACEHOLDER 1",
            "",
        ]
    lines += [
        "#ifdef __cplusplus",
        "extern \"C\" {",
        "#endif",
        "",
        f"// {n} bytes of int8-quantised TFLite-Micro model.",
        "alignas(16) const unsigned char omni_edge_model_data[] = {",
        *rows,
        "};",
        f"const unsigned int omni_edge_model_data_len = {n};",
        "",
    ]
    if threshold is not None:
        lines += [
            "// Reconstruction-MSE threshold above which the device flags OOD.",
            f"const float omni_edge_threshold = {threshold:.6f}f;",
            "",
        ]
    if feat_mean and feat_std:
        assert len(feat_mean) == len(feat_std) == 39, "expected 39-d stats"
        def fmt(arr):
            chunks = [", ".join(f"{v:.6f}f" for v in arr[i:i+6])
                      for i in range(0, len(arr), 6)]
            return ",\n  ".join(chunks)
        lines += [
            "// Per-feature standardisation parameters (mean / std) used at",
            "// training time. Apply (x - mean) / std before feeding to TFLite.",
            "const float omni_edge_feature_mean[39] = {",
            "  " + fmt(feat_mean),
            "};",
            "const float omni_edge_feature_std[39] = {",
            "  " + fmt(feat_std),
            "};",
            "",
        ]
    lines += [
        "#ifdef __cplusplus",
        "}  // extern \"C\"",
        "#endif",
        "",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
    print(f"Wrote {out_path}  ({n} model bytes, "
          f"{'placeholder' if is_placeholder else 'real'} model)")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input",  default="iep2/models/edge_autoencoder.tflite")
    ap.add_argument("--output", default="hardware/esp32/omni_sensor/edge_model_data.h")
    ap.add_argument("--threshold-json", default="iep2/models/edge_threshold.json")
    args = ap.parse_args()

    in_path  = (PROJ / args.input).resolve()
    out_path = (PROJ / args.output).resolve()
    thr_path = (PROJ / args.threshold_json).resolve()

    if not in_path.exists():
        print(f"ERROR: {in_path} not found. Run train_edge_autoencoder.py first.",
              file=sys.stderr)
        sys.exit(1)

    tflite_bytes = in_path.read_bytes()
    is_placeholder = len(tflite_bytes) < 100   # real TFLite headers are >>100 B

    threshold = None
    feat_mean = None
    feat_std  = None
    if thr_path.exists():
        thr = json.loads(thr_path.read_text())
        threshold = float(thr.get("threshold", 0.0))
        if not thr.get("placeholder", False):
            feat_mean = thr.get("feature_mean")
            feat_std  = thr.get("feature_std")

    emit_header(tflite_bytes, threshold, feat_mean, feat_std, out_path,
                is_placeholder)


if __name__ == "__main__":
    main()
