apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mqtt.name }}
  namespace: {{ include "omni-sense.namespace" . }}
  labels:
    {{- include "omni-sense.componentLabels" (dict "component" .Values.mqtt.name "context" .) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "omni-sense.selectorLabels" (dict "component" .Values.mqtt.name "context" .) | nindent 4 }}
  ports:
    - name: mqtts
      port: {{ .Values.mqtt.port }}
      targetPort: mqtts
      protocol: TCP
